const foodEmojis=["\uD83C\uDF46","\uD83E\uDD54","\uD83E\uDD55","\uD83C\uDF3D","\uD83C\uDF36️","\uD83E\uDED1","\uD83E\uDD52","\uD83E\uDD6C","\uD83E\uDD66","\uD83E\uDDC4","\uD83E\uDDC5","\uD83E\uDED8","\uD83C\uDF56","\uD83C\uDF57","\uD83E\uDD69","\uD83E\uDD57","\uD83E\uDD5A","\uD83C\uDF5B","\uD83E\uDD5B","\uD83C\uDF7D️",],randomEmoji=foodEmojis[Math.floor(Math.random()*foodEmojis.length)];function changeFavicon(){document.querySelector("link[rel~='icon']").href=`data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>${randomEmoji}</text></svg>`}function loadSheet(){fetch("https://docs.google.com/spreadsheets/d/e/2PACX-1vQrJgFgWrx8wV5VtwINSpGashMSD2YCgpDLf9_7UiMMdEiWIjqadpugRVPyDfvjAzwRK0PLcmC3E_aK/pubhtml?gid=1252127450&single=true").then(e=>e.text()).then(e=>{let t=new DOMParser,o=t.parseFromString(e,"text/html");o.querySelector("title").innerHTML="Meal Information | Alam Student Palace",o.querySelector("#doc-title").innerHTML="Meal information",o.querySelector("#doc-title").classList.add("head-text"),table=o.querySelector("table > tbody");let n="";for(let r=0;r<76;r++)table.children[r].children[0].children[0].innerHTML=" ",n+=table.children[r].outerHTML;table.innerHTML=n;let a=table.querySelector("tr:nth-child(1) > td:nth-child(3)"),i=new Date,l=new Date;l.setHours(22),l.setMinutes(15),i>l&&a.classList.add("blinking-date"),o.querySelector("#footer > span").innerHTML='Made with ❤️ by <a target="_blank title="Visit portfolio" href="https://jahangir1x.github.io">Jahangir Alam Rocky</a>';let d=o.querySelector("#footer");d.children[1].remove(),d.children[1].remove(),d.children[2].innerHTML="Updated automatically everyday",o.head.innerHTML+='<link rel="stylesheet" href="css/style.css" />',o.head.innerHTML+=`
            <!-- Google tag (gtag.js) -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-KJDQJWPFCC"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
            
              gtag('config', 'G-KJDQJWPFCC');
            </script>
            `,document.write(o.head.outerHTML+o.body.outerHTML),changeFavicon()}).catch(e=>{console.log(e)})}document.addEventListener("DOMContentLoaded",()=>{document.querySelector("#food-emoji").innerHTML=randomEmoji,changeFavicon()}),setTimeout(loadSheet,400);